# Generated by Django 3.1.2 on 2020-10-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=600)),
                ('year', models.CharField(max_length=4)),
                ('authors', models.CharField(max_length=150)),
                ('rank', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.paper')),
            ],
        ),
    ]
